### ISSUE TITLE
SAML: error after SSO

### ISSUE THREAD

**Issue by gicat** [pac4j/spring-webmvc-pac4j-boot-demo#9]
After logging in to OKTA using credentials provided by this example I have the following error:
```
2018-03-29 11:43:21.895 ERROR 1484 --- [nio-8080-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.pac4j.core.exception.TechnicalException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target] with root cause

sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141) ~[na:1.8.0_152]
        at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126) ~[na:1.8.0_152]
        at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280) ~[na:1.8.0_152]
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392) ~[na:1.8.0_152]
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302) ~[na:1.8.0_152]
        at sun.security.validator.Validator.validate(Validator.java:260) ~[na:1.8.0_152]
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324) ~[na:1.8.0_152]
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229) ~[na:1.8.0_152]
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124) ~[na:1.8.0_152]
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1496) ~[na:1.8.0_152]
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216) ~[na:1.8.0_152]
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026) ~[na:1.8.0_152]
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:961) ~[na:1.8.0_152]
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072) ~[na:1.8.0_152]
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385) ~[na:1.8.0_152]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413) ~[na:1.8.0_152]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397) ~[na:1.8.0_152]
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559) ~[na:1.8.0_152]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185) ~[na:1.8.0_152]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564) ~[na:1.8.0_152]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[na:1.8.0_152]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263) ~[na:1.8.0_152]
        at com.nimbusds.jose.util.DefaultResourceRetriever.retrieveResource(DefaultResourceRetriever.java:166) ~[nimbus-jose-jwt-5.4.jar:5.4]
        at org.pac4j.oidc.config.OidcConfiguration.internalInit(OidcConfiguration.java:122) ~[pac4j-oidc-3.0.0-SNAPSHOT.jar:na]
        at org.pac4j.core.util.InitializableObject.init(InitializableObject.java:20) ~[pac4j-core-3.0.0-SNAPSHOT.jar:na]
        at org.pac4j.oidc.client.OidcClient.clientInit(OidcClient.java:45) ~[pac4j-oidc-3.0.0-SNAPSHOT.jar:na]
        at org.pac4j.oidc.client.GoogleOidcClient.clientInit(GoogleOidcClient.java:35) ~[pac4j-oidc-3.0.0-SNAPSHOT.jar:na]
        at org.pac4j.core.client.IndirectClient.internalInit(IndirectClient.java:58) ~[pac4j-core-3.0.0-SNAPSHOT.jar:na]
        at org.pac4j.core.util.InitializableObject.init(InitializableObject.java:20) ~[pac4j-core-3.0.0-SNAPSHOT.jar:na]
        at org.pac4j.core.client.finder.DefaultCallbackClientFinder.find(DefaultCallbackClientFinder.java:36) ~[pac4j-core-3.0.0-SNAPSHOT.jar:na]
        at org.pac4j.core.engine.DefaultCallbackLogic.perform(DefaultCallbackLogic.java:81) ~[pac4j-core-3.0.0-SNAPSHOT.jar:na]
        at org.pac4j.springframework.web.CallbackController.callback(CallbackController.java:59) ~[spring-webmvc-pac4j-3.0.0-SNAPSHOT.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_152]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_152]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_152]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_152]
```

Am I missing some configuration?

**Comment by gicat** [comment]
After modifying Pac4jConfig and removing all configurations and leaving only SAML2Client it works correctly..
